### ISSUE TITLE
能否给个使用指南

### ISSUE THREAD

**Issue by wsqyouth** [wangbjun/gen#4]
文章和代码写的都挺好，代码也写的很优雅，只是要是想运行起来实战下还需要一些前置依赖和API使用demo，不知道能否补充

**Comment by blacksheepaul** [comment]
1. 看项目的go.mod里go的版本，不满足条件就去安装，如果满足条件：
2. 把项目clone下来，在项目文件夹下执行`go mod tidy`，这会把项目需要的依赖安装下来
3. 修改数据库配置，在`app.ini`里面找一下。dsn的大概含义如下:`dsn = 数据库用户:数据库密码@tcp(数据库地址:数据库端口)/数据库名?charset=utf8mb4&parseTime=True&loc=Local`。默认是mysql，没有mysql的话要去安装，没有数据库的话就去创建。
4. 在项目文件夹下执行`go run main.go`，应该能看到输出了许多路由，这时就可以请求api了，比如`curl localhost:8080/api/v1/articles`。
